# PHP-FPM Magento Pool (magento-pool.conf)
#Ini, TOML
[magento]
user = test-ssh
group = clp
listen = /var/run/php/php8.3-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 50
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 20
