# Nginx Site Config (magento.conf)

upstream fastcgi_backend {
    server unix:/var/run/php/php8.3-fpm.sock;
}

server {
    listen 8080;
    server_name _;
    set $MAGE_ROOT /var/www/html/magento;
    include /var/www/html/magento/nginx.conf.sample;
    
    # Logs for troubleshooting
    error_log /var/log/nginx/magento_error.log;
    access_log /var/log/nginx/magento_access.log;
}
